version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: sleep infinity  # Keep container running for development
    depends_on:
      - postgres

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: python -m pytest -v tests/ -p tests.pytest_multi_db --db-type=sqlite
    depends_on:
      - postgres

  # PostgreSQL service for testing
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_mail_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service for running tests with PostgreSQL
  test-postgres:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: python -m pytest -v tests/ -p tests.pytest_multi_db --db-type=postgres --pg-host=postgres --enable-postgres-tests
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
